---
title: "Test Model"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r include=FALSE}
start_time <- Sys.time()

library(recommenderlab)
library(ggplot2)
library(data.table)
library(reshape2)
library(knitr)
#library(base)

```


```{r include=FALSE}
read <- function(fileName, separators) {
    data <- readLines(con <- file(fileName))
    close(con)
    records <- sapply(data, strsplit, split=separators)
    dataFrame <- data.frame(t(sapply(records,c)))
    rownames(dataFrame) <- 1: nrow(dataFrame)
    return(as.data.frame(dataFrame,stringsAsFactors = FALSE))
}


basedir ="data/"
movies = read(paste0(basedir,"movies.dat"), "::")
ratingsdata = read(paste0(basedir,"ratings.dat"), "::")
users = read(paste0(basedir, "users.dat"), "::")
colnames(movies) = c('MovieID', 'title', 'genres')
colnames(ratingsdata) = c('UserID', 'MovieID', 'Rating', 'Timestamp')
colnames(users) = c('UserID', 'Gender', 'Age', 'Occupation', 'Zip-code')

```

```{r}
newratings =  read(paste0(basedir,"newratings.dat"), "::")
colnames(newratings) = c('UserID', 'MovieID', 'Rating', 'Timestamp')
head(newratings)
numberofnewratings = nrow(newratings)


ratings2 = rbind(newratings, ratingsdata)
```


```{r include=FALSE}

#UBCF_N_C = readRDS("C:/MCSDS/CS542 Practical Statistical Learning/Project4/data/model/UBCF_N_C_model.rds")
UBCF_N_C = readRDS("model/UBCF_N_C_model.rds")

#unlink("rec.rds")
#recommenderRegistry$get_entry_names()
#recommenderRegistry$get_entry("POPULAR", dataType = "binaryRatingMatrix")
#recommenderRegistry$get_entry("SVD", dataType = "realRatingMatrix")


newratingsdata <- as(ratings2, 'realRatingMatrix')
#newratingsdata[1:numberofnewratings,]


pred <- predict(UBCF_N_C, newdata = newratingsdata[1:numberofnewratings,], n = 10)
#pred <- predict(UBCF_N_C, newratingsdata, type="ratings")

top10 = as(pred, 'list')[[1]]
top10

```



```{r}
Sys.time() - start_time
```
