---
title: "Project 4: System 2 - User-Based Collaborative Filtering"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## reference: https://raw.githubusercontent.com/ChicagoBoothML/MachineLearning_Fall2015/master/Programming%20Scripts/MovieLens%20Movie%20Recommendation/R/MovieLens_MovieRecommendation.Rmd
## data: https://grouplens.org/datasets/movielens/

```{r include=FALSE}
start_time <- Sys.time()

library(recommenderlab)
library(ggplot2)
library(data.table)
library(reshape2)
library(knitr)

```


```{r include=FALSE}
read <- function(fileName, separators) {
    data <- readLines(con <- file(fileName))
    close(con)
    records <- sapply(data, strsplit, split=separators)
    dataFrame <- data.frame(t(sapply(records,c)))
    rownames(dataFrame) <- 1: nrow(dataFrame)
    return(as.data.frame(dataFrame,stringsAsFactors = FALSE))
}


basedir ="data/"
movies = read(paste0(basedir,"movies.dat"), "::")
ratings = read(paste0(basedir,"ratings.dat"), "::")
users = read(paste0(basedir, "users.dat"), "::")
colnames(movies) = c('MovieID', 'title', 'genres')
colnames(ratings) = c('UserID', 'MovieID', 'Rating', 'Timestamp')
colnames(users) = c('UserID', 'Gender', 'Age', 'Occupation', 'Zip-code')

```


```{r}
nrow(movies)
nrow(ratings)
nrow(users)

```

```{r}
#data <- parse_movielens_1m_data()
#movies <- data$movies
#users <- data$users
#ratings <- data$ratings[ , .(user_id, movie_id, rating)]
#ratings[ , `:=`(user_id = factor(user_id),
#                movie_id = factor(movie_id))]

ratings <- as(ratings, 'realRatingMatrix')


dimnames(ratings)
ratings

```


```{r}
train_proportion <- .5
nb_of_given_ratings_per_test_user <- 10

evaluation_scheme <- evaluationScheme(
  ratings, 
  method='split',
  train=train_proportion,
  k=1,
  given=nb_of_given_ratings_per_test_user)

evaluation_scheme
```


- Training data:
```{r}
ratings_train <- getData(evaluation_scheme, 'train')
ratings_train
```

- Test data: "known"/"given" ratings:
```{r}
ratings_test_known <- getData(evaluation_scheme, 'known')
ratings_test_known
```


- Test data: "unknown" ratings to be predicted and evaluated against:
```{r}
ratings_test_unknown <- getData(evaluation_scheme, 'unknown')
ratings_test_unknown
```



```{r}
recommenderRegistry$get_entry('SVD', dataType='realRatingMatrix')
```


#We train a Latent-Factor CF recommender as follows:

```{r}
# Latent-Factor Collaborative Filtering Recommender
# with matrix factorization by Singular-Value Decomposition (SVD)
 latent_factor_cofi_rec_SVD <- Recommender(
   data=ratings_train,
   method='SVD',            # Item-Based Collaborative Filtering
   parameter=list(
     categories=30,         # number of latent factors
     normalize='center',    # normalizing by subtracting average rating per user;
                            # note that we don't scale by standard deviations here;
                            # we are assuming people rate on the same scale but have
                            # different biases
     method='Pearson'       # use Pearson correlation
   ))

latent_factor_cofi_rec_SVD

model_svd <- Recommender(data = ratings_train, method = "SVD")

model_svd

saveRDS(latent_factor_cofi_rec_SVD, file = "model/latent_factor_cofi_rec_SVD_model.rds")
saveRDS(model_svd, file = "model/model_svd_model.rds")


```




```{r}
# Latent-Factor Collaborative Filtering Recommender
# with matrix factorization by Singular-Value Decomposition (SVD)
 latent_factor_cofi_rec_SVD <- Recommender(
   data=ratings_train,
   method='SVD',            # Item-Based Collaborative Filtering
   parameter=list(
     categories=30,         # number of latent factors
     normalize='center',    # normalizing by subtracting average rating per user;
                            # note that we don't scale by standard deviations here;
                            # we are assuming people rate on the same scale but have
                            # different biases
     method='Pearson'       # use Pearson correlation
   ))


 model_svd <- Recommender(data = ratings_train, method = "SVD")
```


```{r}
latent_factor_cofi_rec_pred <- predict(
  latent_factor_cofi_rec_SVD,
  ratings_test_known,
  type='ratings')

latent_factor_cofi_red_pred_acc <- calcPredictionAccuracy(
   latent_factor_cofi_rec_pred,
   ratings_test_unknown)

latent_factor_cofi_red_pred_acc
```




```{r}
Sys.time() - start_time
```

