---
title: "appTest"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r include=FALSE}
## ui.R
library(shiny)
library(shinydashboard)
library(recommenderlab)
library(data.table)
library(ShinyRatingInput)
library(shinyjs)
library(shinythemes)
library(shinydashboard)

```

```{r}

source('functions/helpers.R')

# load functions
source('functions/cf_algorithm.R') # collaborative filtering
source('functions/similarity_measures.R') # similarity measures

# define functions
get_user_ratings <- function(value_list) {
  dat <- data.table(book_id = sapply(strsplit(names(value_list), "_"), function(x) ifelse(length(x) > 1, x[[2]], NA)),
                    rating = unlist(as.character(value_list)))
  dat <- dat[!is.null(rating) & !is.na(book_id)]
  dat[rating == " ", rating := 0]
  dat[, ':=' (book_id = as.numeric(book_id), rating = as.numeric(rating))]
  dat <- dat[rating > 0]
  
  # get the indices of the ratings
  # add the user ratings to the existing rating matrix
  user_ratings <- sparseMatrix(i = dat$book_id, 
                               j = rep(1,nrow(dat)), 
                               x = dat$rating, 
                               dims = c(nrow(ratingmat), 1))
}

# read in data
#books <- fread('data/books.csv')
#ratings <- fread('data/ratings_cleaned.csv')

basedir ="data/"
movies <- read(paste0(basedir,"aggr200.dat"), "::")

colnames(movies) = c( 'MovieID', 'AveRating', 'title', 'genres')
movies$MovieID <- as.numeric(movies$MovieID)


      num_rows <- 20
      num_books <- 6 # books per row
      
      lapply(1:num_rows, function(i) {
        lapply(1:num_books, function(j) {
                   paste0( "movieImages/", movies$MovieID[(i - 1) * num_books + j],  ".jpg")
                   paste0( movies$title[(i - 1) * num_books + j]) 
                   movies$MovieID[(i - 1) * num_books + j]
        })
      })


```
